print("Olá Mundo!")
print("Meu primeiro programa em Python")
print("Estou aprendendo Python")
print("Python é uma linguagem de programação muito legal!")
print("Estou animado para continuar aprendendo mais sobre Python!")
print("Vamos criar muitos programas legais juntos!")
print("Obrigado por acompanhar meu primeiro programa em Python!")
print("Até a próxima!")